### ISSUE TITLE
Extra spaces in store paths

### ISSUE THREAD

**Issue by ilikeavocadoes** [cid-chan/peerix#3]
When activating two peerix instances, one local, and one on another machine in the same network, `nixos-rebuild` fails with the following: `error: store path 'nfc84fq55dbzxa6f6wsc67ib9ggm5yfn-nixos-manual-html.drv ' contains illegal character ' '`. Unfortunately, the error is transient, and I cannot reproduce it reliably. Every time I rerun `nixos-rebuild`, a different store path is emitted along with the error. Maybe something wrong with Narinfo parsing?

**Comment by cid-chan** [comment]
Can you tell me if you are using Nix 2.4-rc or Nix 2.3?

It starts happening with my installation too, but only after I switched to Nix 2.4.

**Comment by cid-chan** [comment]
I can reproduce this error even when peerix is turned off.

![image](https://user-images.githubusercontent.com/76440879/139911859-9fb76e65-bc6f-42e2-a899-2abf38a50c03.png)
![image](https://user-images.githubusercontent.com/76440879/139912211-4bee3970-4e3b-432e-bf23-2cb153eadf4a.png)

I guess this might be an error in nix.

**Comment by ilikeavocadoes** [comment]
I'm using Nix version `2.4pre20211006_53e4794`. The error disappears when I turn off Peerix on the other system, which is why I assumed this is related to Peerix. As you reproduced the issue with another tool, this must be due to some feature Peerix uses. I'll close this issue.

**Comment by MaeIsBad** [comment]
I think the issue is actually with peerix. If you remove the space from the end of the string at https://github.com/cid-chan/peerix/blob/master/peerix/store.py#L25 it starts working again
